version: "3.8"

services:
  # FastAPI application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      # Mount source code for hot reload
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  # Redis cache
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      # Persist Redis data
      - redis_data:/data
    networks:
      - app-network

  # Redis admin interface (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
