services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/flask_dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=flask_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
