# Basic pre-commit configuration - to be enhanced in Module 3
# This file will be configured step by step following the guide

repos:
  - repo: local
    hooks:
      - id: placeholder
        name: placeholder
        entry: echo "Configure pre-commit hooks following Module 3 guide"
        language: system
