# Basic pyproject.toml - to be enhanced in Module 3
[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-quality-example"
version = "0.1.0"
description = "FastAPI application with code quality tools"
