version: "3.8"

services:
  # Flask application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:password@db:5432/devdb
      - FLASK_DEBUG=1
    volumes:
      # Mount source code for hot reload
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with sample data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Database administration tool (optional)
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
