name: CI - Flask App

on:
  push:
    paths:
      - 'examples/flask-app/**'
  pull_request:
    paths:
      - 'examples/flask-app/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/flask-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Check formatting with black
        run: black --check .
      - name: Type check with mypy
        run: mypy .
      - name: Run tests with pytest
        run: pytest
      - name: Build Docker image
        run: docker build -t flask-app:ci .
