name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [main, module-04-cicd]
    paths:
      - "examples/fastapi-cicd/**"
  pull_request:
    branches: [main, module-04-cicd]
    paths:
      - "examples/fastapi-cicd/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fastapi-cicd

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          cd examples/fastapi-cicd
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint with Ruff
        run: |
          cd examples/fastapi-cicd
          ruff check --output-format=github .
          ruff format --check .

      - name: Type checking with Pyright
        run: |
          cd examples/fastapi-cicd
          pyright .

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
        run: |
          cd examples/fastapi-cicd
          pytest tests/ -v --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./examples/fastapi-cicd/coverage.xml
          fail_ci_if_error: true

  performance:
    runs-on: ubuntu-latest
    needs: test

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd examples/fastapi-cicd
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install locust

      - name: Start FastAPI app
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
        run: |
          cd examples/fastapi-cicd
          uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Run performance tests
        run: |
          cd examples/fastapi-cicd
          locust --headless --users 100 --spawn-rate 10 --run-time 30s --host http://localhost:8000 -f tests/locustfile.py

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd examples/fastapi-cicd
          python -m pip install --upgrade pip
          pip install safety bandit semgrep

      - name: Run safety check
        run: |
          cd examples/fastapi-cicd
          safety check -r requirements.txt

      - name: Run bandit security linter
        run: |
          cd examples/fastapi-cicd
          bandit -r . -f json -o bandit-report.json

      - name: Run Semgrep
        run: |
          cd examples/fastapi-cicd
          semgrep --config=auto --json --output=semgrep-report.json .

      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-scan-results
          path: |
            examples/fastapi-cicd/bandit-report.json
            examples/fastapi-cicd/semgrep-report.json

  build-and-push:
    needs: [test, security]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: examples/fastapi-cicd
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Deploy to production
        run: |
          echo "🚀 Deploying FastAPI application to production"
          echo "Image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest"
          # Add your deployment commands here
          # Examples: kubectl, docker-compose, cloud provider CLIs

      - name: Run smoke tests
        run: |
          echo "🧪 Running post-deployment smoke tests"
          # Add smoke tests for production deployment
          curl -f https://your-app-domain.com/health || exit 1
